name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install

    - name: format code
      run: make format
    - name: check the code
      run: make lint
    - name: test the code
      run: make test

    
